/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.evetech.esi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * content object
 */
@ApiModel(description = "content object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-30T13:35:06.976-04:00")
public class GetCharactersCharacterIdPlanetsPlanetIdContent {
  @SerializedName("amount")
  private Long amount = null;

  @SerializedName("type_id")
  private Integer typeId = null;

  public GetCharactersCharacterIdPlanetsPlanetIdContent amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * amount integer
   * @return amount
  **/
  @ApiModelProperty(example = "null", required = true, value = "amount integer")
  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public GetCharactersCharacterIdPlanetsPlanetIdContent typeId(Integer typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * type_id integer
   * @return typeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "type_id integer")
  public Integer getTypeId() {
    return typeId;
  }

  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdPlanetsPlanetIdContent getCharactersCharacterIdPlanetsPlanetIdContent = (GetCharactersCharacterIdPlanetsPlanetIdContent) o;
    return Objects.equals(this.amount, getCharactersCharacterIdPlanetsPlanetIdContent.amount) &&
        Objects.equals(this.typeId, getCharactersCharacterIdPlanetsPlanetIdContent.typeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, typeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdPlanetsPlanetIdContent {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

