/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.evetech.esi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import net.evetech.esi.models.GetCorporationsCorporationIdStarbasesStarbaseIdFuel;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-11T14:20:13.441-05:00")
public class GetCorporationsCorporationIdStarbasesStarbaseIdOk {
  @SerializedName("allow_alliance_members")
  private Boolean allowAllianceMembers = null;

  @SerializedName("allow_corporation_members")
  private Boolean allowCorporationMembers = null;

  /**
   * Who can anchor starbase (POS) and its structures
   */
  public enum AnchorEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    AnchorEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("anchor")
  private AnchorEnum anchor = null;

  @SerializedName("attack_if_at_war")
  private Boolean attackIfAtWar = null;

  @SerializedName("attack_if_other_security_status_dropping")
  private Boolean attackIfOtherSecurityStatusDropping = null;

  @SerializedName("attack_security_status_threshold")
  private Float attackSecurityStatusThreshold = null;

  @SerializedName("attack_standing_threshold")
  private Float attackStandingThreshold = null;

  /**
   * Who can take fuel blocks out of the starbase (POS)'s fuel bay
   */
  public enum FuelBayTakeEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    FuelBayTakeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("fuel_bay_take")
  private FuelBayTakeEnum fuelBayTake = null;

  /**
   * Who can view the starbase (POS)'s fule bay. Characters either need to have required role or belong to the starbase (POS) owner's corporation or alliance, as described by the enum, all other access settings follows the same scheme
   */
  public enum FuelBayViewEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    FuelBayViewEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("fuel_bay_view")
  private FuelBayViewEnum fuelBayView = null;

  @SerializedName("fuels")
  private List<GetCorporationsCorporationIdStarbasesStarbaseIdFuel> fuels = new ArrayList<GetCorporationsCorporationIdStarbasesStarbaseIdFuel>();

  /**
   * Who can offline starbase (POS) and its structures
   */
  public enum OfflineEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    OfflineEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("offline")
  private OfflineEnum offline = null;

  /**
   * Who can online starbase (POS) and its structures
   */
  public enum OnlineEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    OnlineEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("online")
  private OnlineEnum online = null;

  /**
   * Who can unanchor starbase (POS) and its structures
   */
  public enum UnanchorEnum {
    @SerializedName("alliance_member")
    ALLIANCE_MEMBER("alliance_member"),
    
    @SerializedName("config_starbase_equipment_role")
    CONFIG_STARBASE_EQUIPMENT_ROLE("config_starbase_equipment_role"),
    
    @SerializedName("corporation_member")
    CORPORATION_MEMBER("corporation_member"),
    
    @SerializedName("starbase_fuel_technician_role")
    STARBASE_FUEL_TECHNICIAN_ROLE("starbase_fuel_technician_role");

    private String value;

    UnanchorEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("unanchor")
  private UnanchorEnum unanchor = null;

  @SerializedName("use_alliance_standings")
  private Boolean useAllianceStandings = null;

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk allowAllianceMembers(Boolean allowAllianceMembers) {
    this.allowAllianceMembers = allowAllianceMembers;
    return this;
  }

   /**
   * allow_alliance_members boolean
   * @return allowAllianceMembers
  **/
  @ApiModelProperty(example = "null", required = true, value = "allow_alliance_members boolean")
  public Boolean getAllowAllianceMembers() {
    return allowAllianceMembers;
  }

  public void setAllowAllianceMembers(Boolean allowAllianceMembers) {
    this.allowAllianceMembers = allowAllianceMembers;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk allowCorporationMembers(Boolean allowCorporationMembers) {
    this.allowCorporationMembers = allowCorporationMembers;
    return this;
  }

   /**
   * allow_corporation_members boolean
   * @return allowCorporationMembers
  **/
  @ApiModelProperty(example = "null", required = true, value = "allow_corporation_members boolean")
  public Boolean getAllowCorporationMembers() {
    return allowCorporationMembers;
  }

  public void setAllowCorporationMembers(Boolean allowCorporationMembers) {
    this.allowCorporationMembers = allowCorporationMembers;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk anchor(AnchorEnum anchor) {
    this.anchor = anchor;
    return this;
  }

   /**
   * Who can anchor starbase (POS) and its structures
   * @return anchor
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can anchor starbase (POS) and its structures")
  public AnchorEnum getAnchor() {
    return anchor;
  }

  public void setAnchor(AnchorEnum anchor) {
    this.anchor = anchor;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk attackIfAtWar(Boolean attackIfAtWar) {
    this.attackIfAtWar = attackIfAtWar;
    return this;
  }

   /**
   * attack_if_at_war boolean
   * @return attackIfAtWar
  **/
  @ApiModelProperty(example = "null", required = true, value = "attack_if_at_war boolean")
  public Boolean getAttackIfAtWar() {
    return attackIfAtWar;
  }

  public void setAttackIfAtWar(Boolean attackIfAtWar) {
    this.attackIfAtWar = attackIfAtWar;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk attackIfOtherSecurityStatusDropping(Boolean attackIfOtherSecurityStatusDropping) {
    this.attackIfOtherSecurityStatusDropping = attackIfOtherSecurityStatusDropping;
    return this;
  }

   /**
   * attack_if_other_security_status_dropping boolean
   * @return attackIfOtherSecurityStatusDropping
  **/
  @ApiModelProperty(example = "null", required = true, value = "attack_if_other_security_status_dropping boolean")
  public Boolean getAttackIfOtherSecurityStatusDropping() {
    return attackIfOtherSecurityStatusDropping;
  }

  public void setAttackIfOtherSecurityStatusDropping(Boolean attackIfOtherSecurityStatusDropping) {
    this.attackIfOtherSecurityStatusDropping = attackIfOtherSecurityStatusDropping;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk attackSecurityStatusThreshold(Float attackSecurityStatusThreshold) {
    this.attackSecurityStatusThreshold = attackSecurityStatusThreshold;
    return this;
  }

   /**
   * Starbase (POS) will attack if target's security standing is lower than this value
   * @return attackSecurityStatusThreshold
  **/
  @ApiModelProperty(example = "null", value = "Starbase (POS) will attack if target's security standing is lower than this value")
  public Float getAttackSecurityStatusThreshold() {
    return attackSecurityStatusThreshold;
  }

  public void setAttackSecurityStatusThreshold(Float attackSecurityStatusThreshold) {
    this.attackSecurityStatusThreshold = attackSecurityStatusThreshold;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk attackStandingThreshold(Float attackStandingThreshold) {
    this.attackStandingThreshold = attackStandingThreshold;
    return this;
  }

   /**
   * Starbase (POS) will attack if target's standing is lower than this value
   * @return attackStandingThreshold
  **/
  @ApiModelProperty(example = "null", value = "Starbase (POS) will attack if target's standing is lower than this value")
  public Float getAttackStandingThreshold() {
    return attackStandingThreshold;
  }

  public void setAttackStandingThreshold(Float attackStandingThreshold) {
    this.attackStandingThreshold = attackStandingThreshold;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk fuelBayTake(FuelBayTakeEnum fuelBayTake) {
    this.fuelBayTake = fuelBayTake;
    return this;
  }

   /**
   * Who can take fuel blocks out of the starbase (POS)'s fuel bay
   * @return fuelBayTake
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can take fuel blocks out of the starbase (POS)'s fuel bay")
  public FuelBayTakeEnum getFuelBayTake() {
    return fuelBayTake;
  }

  public void setFuelBayTake(FuelBayTakeEnum fuelBayTake) {
    this.fuelBayTake = fuelBayTake;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk fuelBayView(FuelBayViewEnum fuelBayView) {
    this.fuelBayView = fuelBayView;
    return this;
  }

   /**
   * Who can view the starbase (POS)'s fule bay. Characters either need to have required role or belong to the starbase (POS) owner's corporation or alliance, as described by the enum, all other access settings follows the same scheme
   * @return fuelBayView
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can view the starbase (POS)'s fule bay. Characters either need to have required role or belong to the starbase (POS) owner's corporation or alliance, as described by the enum, all other access settings follows the same scheme")
  public FuelBayViewEnum getFuelBayView() {
    return fuelBayView;
  }

  public void setFuelBayView(FuelBayViewEnum fuelBayView) {
    this.fuelBayView = fuelBayView;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk fuels(List<GetCorporationsCorporationIdStarbasesStarbaseIdFuel> fuels) {
    this.fuels = fuels;
    return this;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk addFuelsItem(GetCorporationsCorporationIdStarbasesStarbaseIdFuel fuelsItem) {
    this.fuels.add(fuelsItem);
    return this;
  }

   /**
   * Fuel blocks and other things that will be consumed when operating a starbase (POS)
   * @return fuels
  **/
  @ApiModelProperty(example = "null", value = "Fuel blocks and other things that will be consumed when operating a starbase (POS)")
  public List<GetCorporationsCorporationIdStarbasesStarbaseIdFuel> getFuels() {
    return fuels;
  }

  public void setFuels(List<GetCorporationsCorporationIdStarbasesStarbaseIdFuel> fuels) {
    this.fuels = fuels;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk offline(OfflineEnum offline) {
    this.offline = offline;
    return this;
  }

   /**
   * Who can offline starbase (POS) and its structures
   * @return offline
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can offline starbase (POS) and its structures")
  public OfflineEnum getOffline() {
    return offline;
  }

  public void setOffline(OfflineEnum offline) {
    this.offline = offline;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk online(OnlineEnum online) {
    this.online = online;
    return this;
  }

   /**
   * Who can online starbase (POS) and its structures
   * @return online
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can online starbase (POS) and its structures")
  public OnlineEnum getOnline() {
    return online;
  }

  public void setOnline(OnlineEnum online) {
    this.online = online;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk unanchor(UnanchorEnum unanchor) {
    this.unanchor = unanchor;
    return this;
  }

   /**
   * Who can unanchor starbase (POS) and its structures
   * @return unanchor
  **/
  @ApiModelProperty(example = "null", required = true, value = "Who can unanchor starbase (POS) and its structures")
  public UnanchorEnum getUnanchor() {
    return unanchor;
  }

  public void setUnanchor(UnanchorEnum unanchor) {
    this.unanchor = unanchor;
  }

  public GetCorporationsCorporationIdStarbasesStarbaseIdOk useAllianceStandings(Boolean useAllianceStandings) {
    this.useAllianceStandings = useAllianceStandings;
    return this;
  }

   /**
   * True if the starbase (POS) is using alliance standings, otherwise using corporation's
   * @return useAllianceStandings
  **/
  @ApiModelProperty(example = "null", required = true, value = "True if the starbase (POS) is using alliance standings, otherwise using corporation's")
  public Boolean getUseAllianceStandings() {
    return useAllianceStandings;
  }

  public void setUseAllianceStandings(Boolean useAllianceStandings) {
    this.useAllianceStandings = useAllianceStandings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdStarbasesStarbaseIdOk getCorporationsCorporationIdStarbasesStarbaseIdOk = (GetCorporationsCorporationIdStarbasesStarbaseIdOk) o;
    return Objects.equals(this.allowAllianceMembers, getCorporationsCorporationIdStarbasesStarbaseIdOk.allowAllianceMembers) &&
        Objects.equals(this.allowCorporationMembers, getCorporationsCorporationIdStarbasesStarbaseIdOk.allowCorporationMembers) &&
        Objects.equals(this.anchor, getCorporationsCorporationIdStarbasesStarbaseIdOk.anchor) &&
        Objects.equals(this.attackIfAtWar, getCorporationsCorporationIdStarbasesStarbaseIdOk.attackIfAtWar) &&
        Objects.equals(this.attackIfOtherSecurityStatusDropping, getCorporationsCorporationIdStarbasesStarbaseIdOk.attackIfOtherSecurityStatusDropping) &&
        Objects.equals(this.attackSecurityStatusThreshold, getCorporationsCorporationIdStarbasesStarbaseIdOk.attackSecurityStatusThreshold) &&
        Objects.equals(this.attackStandingThreshold, getCorporationsCorporationIdStarbasesStarbaseIdOk.attackStandingThreshold) &&
        Objects.equals(this.fuelBayTake, getCorporationsCorporationIdStarbasesStarbaseIdOk.fuelBayTake) &&
        Objects.equals(this.fuelBayView, getCorporationsCorporationIdStarbasesStarbaseIdOk.fuelBayView) &&
        Objects.equals(this.fuels, getCorporationsCorporationIdStarbasesStarbaseIdOk.fuels) &&
        Objects.equals(this.offline, getCorporationsCorporationIdStarbasesStarbaseIdOk.offline) &&
        Objects.equals(this.online, getCorporationsCorporationIdStarbasesStarbaseIdOk.online) &&
        Objects.equals(this.unanchor, getCorporationsCorporationIdStarbasesStarbaseIdOk.unanchor) &&
        Objects.equals(this.useAllianceStandings, getCorporationsCorporationIdStarbasesStarbaseIdOk.useAllianceStandings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowAllianceMembers, allowCorporationMembers, anchor, attackIfAtWar, attackIfOtherSecurityStatusDropping, attackSecurityStatusThreshold, attackStandingThreshold, fuelBayTake, fuelBayView, fuels, offline, online, unanchor, useAllianceStandings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdStarbasesStarbaseIdOk {\n");
    
    sb.append("    allowAllianceMembers: ").append(toIndentedString(allowAllianceMembers)).append("\n");
    sb.append("    allowCorporationMembers: ").append(toIndentedString(allowCorporationMembers)).append("\n");
    sb.append("    anchor: ").append(toIndentedString(anchor)).append("\n");
    sb.append("    attackIfAtWar: ").append(toIndentedString(attackIfAtWar)).append("\n");
    sb.append("    attackIfOtherSecurityStatusDropping: ").append(toIndentedString(attackIfOtherSecurityStatusDropping)).append("\n");
    sb.append("    attackSecurityStatusThreshold: ").append(toIndentedString(attackSecurityStatusThreshold)).append("\n");
    sb.append("    attackStandingThreshold: ").append(toIndentedString(attackStandingThreshold)).append("\n");
    sb.append("    fuelBayTake: ").append(toIndentedString(fuelBayTake)).append("\n");
    sb.append("    fuelBayView: ").append(toIndentedString(fuelBayView)).append("\n");
    sb.append("    fuels: ").append(toIndentedString(fuels)).append("\n");
    sb.append("    offline: ").append(toIndentedString(offline)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    unanchor: ").append(toIndentedString(unanchor)).append("\n");
    sb.append("    useAllianceStandings: ").append(toIndentedString(useAllianceStandings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

