/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package is.ccp.tech.esi;

import is.ccp.tech.ApiException;
import is.ccp.tech.esi.models.Forbidden;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdAlliancehistory200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdBlueprints200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdContainersLogs200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdDivisionsOk;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdFacilities200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdIconsNotFound;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdIconsOk;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdMedals200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdMedalsIssued200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdMembers200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdMembersTitles200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdMembertracking200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdNotFound;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdOk;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdRoles200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdRolesHistory200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdShareholders200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdStandings200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdStarbases200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdStarbasesStarbaseIdOk;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdStructures200Ok;
import is.ccp.tech.esi.models.GetCorporationsCorporationIdTitles200Ok;
import is.ccp.tech.esi.models.GetCorporationsNames200Ok;
import is.ccp.tech.esi.models.InternalServerError;
import is.ccp.tech.esi.models.PutCorporationsCorporationIdStructuresStructureIdNewSchedule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CorporationApi
 */
@Ignore
public class CorporationApiTest {

    private final CorporationApi api = new CorporationApi();

    
    /**
     * Get corporation information
     *
     * Public information about a corporation  --- Alternate route: &#x60;/v3/corporations/{corporation_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdOk response = api.getCorporationsCorporationId(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get alliance history
     *
     * Get a list of all the alliances a corporation has been a member of  --- Alternate route: &#x60;/v2/corporations/{corporation_id}/alliancehistory/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/alliancehistory/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdAlliancehistoryTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdAlliancehistory200Ok> response = api.getCorporationsCorporationIdAlliancehistory(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation blueprints
     *
     * Returns a list of blueprints the corporation owns  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/blueprints/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/blueprints/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/blueprints/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdBlueprintsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdBlueprints200Ok> response = api.getCorporationsCorporationIdBlueprints(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get all corporation ALSC logs
     *
     * Returns logs recorded in the past seven days from all audit log secure containers (ALSC) owned by a given corporation  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/containers/logs/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/containers/logs/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/containers/logs/&#x60;  --- This route is cached for up to 600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdContainersLogsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdContainersLogs200Ok> response = api.getCorporationsCorporationIdContainersLogs(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation divisions
     *
     * Return corporation hangar and wallet division names, only show if a division is not using the default name  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/divisions/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/divisions/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/divisions/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdDivisionsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdDivisionsOk response = api.getCorporationsCorporationIdDivisions(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation facilities
     *
     * Return a corporation&#39;s facilities  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/facilities/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/facilities/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/facilities/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdFacilitiesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdFacilities200Ok> response = api.getCorporationsCorporationIdFacilities(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation icon
     *
     * Get the icon urls for a corporation  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/icons/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/icons/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/icons/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdIconsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdIconsOk response = api.getCorporationsCorporationIdIcons(corporationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation medals
     *
     * Returns a corporation&#39;s medals  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/medals/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/medals/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/medals/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMedalsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMedals200Ok> response = api.getCorporationsCorporationIdMedals(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation issued medals
     *
     * Returns medals issued by a corporation  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/medals/issued/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/medals/issued/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/medals/issued/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMedalsIssuedTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMedalsIssued200Ok> response = api.getCorporationsCorporationIdMedalsIssued(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation members
     *
     * Read the current list of members if the calling character is a member.  --- Alternate route: &#x60;/v2/corporations/{corporation_id}/members/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/members/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMembers200Ok> response = api.getCorporationsCorporationIdMembers(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation member limit
     *
     * Return a corporation&#39;s member limit, not including CEO himself  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/members/limit/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/members/limit/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/members/limit/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersLimitTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        Integer response = api.getCorporationsCorporationIdMembersLimit(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation&#39;s members&#39; titles
     *
     * Returns a corporation&#39;s members&#39; titles  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/members/titles/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/members/titles/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/members/titles/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembersTitlesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMembersTitles200Ok> response = api.getCorporationsCorporationIdMembersTitles(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Track corporation members
     *
     * Returns additional information about a corporation&#39;s members which helps tracking their activities  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/membertracking/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/membertracking/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/membertracking/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdMembertrackingTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdMembertracking200Ok> response = api.getCorporationsCorporationIdMembertracking(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation member roles
     *
     * Return the roles of all members if the character has the personnel manager role or any grantable role.  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/roles/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/roles/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/roles/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdRolesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdRoles200Ok> response = api.getCorporationsCorporationIdRoles(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation member roles history
     *
     * Return how roles have changed for a coporation&#39;s members, up to a month  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/roles/history/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/roles/history/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/roles/history/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdRolesHistoryTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdRolesHistory200Ok> response = api.getCorporationsCorporationIdRolesHistory(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation members
     *
     * Return the current member list of a corporation, the token&#39;s character need to be a member of the corporation.  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/shareholders/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/shareholders/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/shareholders/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdShareholdersTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdShareholders200Ok> response = api.getCorporationsCorporationIdShareholders(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation standings
     *
     * Return corporation standings from agents, NPC corporations, and factions  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/standings/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/standings/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/standings/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStandingsTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdStandings200Ok> response = api.getCorporationsCorporationIdStandings(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation starbases (POSes)
     *
     * Returns list of corporation starbases (POSes)  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/starbases/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/starbases/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/starbases/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStarbasesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdStarbases200Ok> response = api.getCorporationsCorporationIdStarbases(corporationId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get starbase (POS) detail
     *
     * Returns various settings and fuels of a starbase (POS)  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/starbases/{starbase_id}/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/starbases/{starbase_id}/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/starbases/{starbase_id}/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStarbasesStarbaseIdTest() throws ApiException {
        Integer corporationId = null;
        Long starbaseId = null;
        Integer systemId = null;
        String datasource = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCorporationsCorporationIdStarbasesStarbaseIdOk response = api.getCorporationsCorporationIdStarbasesStarbaseId(corporationId, starbaseId, systemId, datasource, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation structures
     *
     * Get a list of corporation structures  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/structures/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/structures/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/structures/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdStructuresTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String language = null;
        Integer page = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdStructures200Ok> response = api.getCorporationsCorporationIdStructures(corporationId, datasource, language, page, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation titles
     *
     * Returns a corporation&#39;s titles  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/titles/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/titles/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/titles/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdTitlesTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdTitles200Ok> response = api.getCorporationsCorporationIdTitles(corporationId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation names
     *
     * Resolve a set of corporation IDs to corporation names  --- Alternate route: &#x60;/v1/corporations/names/&#x60;  Alternate route: &#x60;/legacy/corporations/names/&#x60;  --- This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsNamesTest() throws ApiException {
        List<Long> corporationIds = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsNames200Ok> response = api.getCorporationsNames(corporationIds, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get npc corporations
     *
     * Get a list of npc corporations  --- Alternate route: &#x60;/v1/corporations/npccorps/&#x60;  Alternate route: &#x60;/legacy/corporations/npccorps/&#x60;  Alternate route: &#x60;/dev/corporations/npccorps/&#x60;  --- This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsNpccorpsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getCorporationsNpccorps(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Update structure vulnerability schedule
     *
     * Update the vulnerability window schedule of a corporation structure  --- Alternate route: &#x60;/v1/corporations/{corporation_id}/structures/{structure_id}/&#x60;  Alternate route: &#x60;/legacy/corporations/{corporation_id}/structures/{structure_id}/&#x60;  Alternate route: &#x60;/dev/corporations/{corporation_id}/structures/{structure_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putCorporationsCorporationIdStructuresStructureIdTest() throws ApiException {
        Integer corporationId = null;
        List<PutCorporationsCorporationIdStructuresStructureIdNewSchedule> newSchedule = null;
        Long structureId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putCorporationsCorporationIdStructuresStructureId(corporationId, newSchedule, structureId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
